### ISSUE TITLE
can not reproduce claimed performance

### ISSUE THREAD

**Issue by rafa-cxg** [ChCh1999/RTPB#1] opened 2022-04-14 06:31 UTC
hi, thanks for your excellent works!

However, I am running DualTrans+CB code, but I can not get satisfactory results. (mR@100 only 15). Could you show us your training log results? 
                                                                                                                                                                                       Thank you!

**Comment by rafa-cxg** [comment] 2022-04-15 15:28
hi!
I would like to ask, could you please provide this pretrained detector checkpoint for us? For reproducing the performance.
Thanks
![image](https://user-images.githubusercontent.com/49938663/163589494-01136c18-906b-4ee9-9229-a72e8fd55c40.png)

**Comment by ChCh1999** [comment] 2022-04-19 02:20
Sorry about the delay, we will release all of the checkpoints soon.
You can download the detector checkpoint from the following temporary link: 
http://s3.cn-north-1.jdcloud-oss.com/jde-oss-002/chenchao278/model/detector_base_x32/model_final.pth

**Comment by rafa-cxg** [comment] 2022-04-19 03:12
Thanks, We are looking forward to your update.

**Comment by rafa-cxg** [comment] 2022-04-24 02:52
Hi, this is my training log, with script dual+cb.
However, the result is less than 10%, I am confused.  Can you tell me why? thanks.
![image](https://user-images.githubusercontent.com/49938663/164954031-7167e7a5-bb13-46b7-9c95-817e631e1e64.png)

**Comment by ChCh1999** [comment] 2022-04-24 03:45
I'm not sure what happened. In your log, the recall rate for the most of relationships is 0, which is strange. Here is my log of dual+cb on the SGCls task.
[sgcls_dt_cb.txt](https://github.com/ChCh1999/RTPB/files/8548981/sgcls_dt_cb.txt)
You can check it and try to find out what happened in your experiment first. 
And I'll also try to reproduce your experiment.

**Comment by rafa-cxg** [comment] 2022-04-24 04:27
Thanks, but do you have sgdet  task  training log?

**Comment by ChCh1999** [comment] 2022-04-24 05:26
Here is one of our SGDet log files. You can check it and try to locate your problem by yourself first.
[sgdet_dt_cb.txt](https://github.com/ChCh1999/RTPB/files/8549064/sgdet_dt_cb.txt)

**Comment by rafa-cxg** [comment] 2022-04-24 06:52
Thank you!
 However, when I was checking  [sgdet_dt_cb.txt](https://github.com/ChCh1999/RTPB/files/8549064/sgdet_dt_cb.txt) ,I found `PENALTY `configrations are also existed in `ROI_BOX_HEAD` , which is not in default.py or any code. Is something missing?
![image](https://user-images.githubusercontent.com/49938663/164960605-de878f01-361f-4a99-bf34-07278de9a989.png)
and also `RELATION_NET` :
![image](https://user-images.githubusercontent.com/49938663/164960721-b5c97ce2-ce9f-442a-8630-1537b64cd008.png)

**Comment by ChCh1999** [comment] 2022-04-24 07:21
This log is produced by an elder version of code. We removed those redundant config items. The configurations about  `PENALTY` have been merged to `MODEL.ROI_RELATION_HEAD.BIAS_MODULE.*`
Besides, I run `scripts/sgg/DT_base_cb.sh` and I get the following performance at iteration 4000. It seems to be quite different from your result. Please further check your experiment setting and other details.
![image](https://user-images.githubusercontent.com/34148951/164964718-01d6d9a0-ac12-4151-8333-179d2f8da04c.png)

**Comment by ChCh1999** [comment] 2022-04-25 02:29
Here is the log file with the script  `scripts/sgg/DT_base_cb.sh` produced by the current code. Hope it helps with your experiments.
[sgdet_dt_cb.txt](https://github.com/ChCh1999/RTPB/files/8551190/sgdet_dt_cb.txt)

**Comment by rafa-cxg** [comment] 2022-04-26 15:19
Hi, thanks for your patience. I re-download  code and  making sure anything is  following  the instruction. I got 13% mean recall in sgdet task. this is my log.txt.[https://seunic-my.sharepoint.cn/:t:/g/personal/220201747_seu_edu_cn/EYpDlgMBKYFHpJpe5s-f784BjyKAfGXf0fN_fk361w8elw?e=4Gtj7D](url). It would be great if you can check what's wrong. thanks!

**Comment by ChCh1999** [comment] 2022-04-26 15:27
It seems you didn't use our cb method, the result is produced by Dual Transformer. Use the configuration `MODEL.ROI_RELATION_HEAD.BIAS_MODULE.USE_PENALTY True MODEL.ROI_RELATION_HEAD.BIAS_MODULE.PENALTY_BIAS.PENALTY_TYPE count_bias` to apply our cb or just run the script `scripts/sgg/DT_base_cb.sh`.
![image](https://user-images.githubusercontent.com/34148951/165335980-db0e7e9d-379b-4009-8b04-dcaa8f441e62.png)
![image](https://user-images.githubusercontent.com/34148951/165336147-3250e17e-025e-4911-933b-9937e6360b4a.png)

**Comment by rafa-cxg** [comment] 2022-04-28 14:08
Thanks...
Now i have added USE_PENALTY and PENALTY_TYPE  , configration should be same now. This is  new [log.txt.](https://seunic-my.sharepoint.cn/personal/220201747_seu_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F220201747%5Fseu%5Fedu%5Fcn%2FDocuments%2Flog%2Etxt&parent=%2Fpersonal%2F220201747%5Fseu%5Fedu%5Fcn%2FDocuments&ga=1)
But best performance is 14%. Still not the best. Do you think is there another problem? Thank you!
![image](https://user-images.githubusercontent.com/49938663/165771603-058159b5-c186-4178-a8f8-3d5436594865.png)

**Closed as completed** 2022-05-17 06:50 UTC
Labels: help wanted
